### PR TITLE
Resolve NullReferenceException when DrawsHeatRange = false

### PR DESCRIPTION
**Pull request by ibebbs**
#### Summary

Resolve NullReferenceException when DrawsHeatRange = false
Fixed up nuget packaging for UWP assemblies.

#### Solves 

NullReferenceException in HeatSeries when DrawsHeatRange = false
'LiveCharts.Uwp.dll' not found when packaging UWP into nuget package

### CODE REVIEW

**Comment by beto-rodriguez** [comment]
Thanks for the help in the Uwp packaging I was having a bad time there

**Comment by ibebbs** [comment]
No worries. I've got a few more commits incoming which I haven't sync'd to my fork yet as I'm still unable to use the UWP package in a UWP solution (installs fine but no LiveCharts.Uwp namespace available).

**Comment by ibebbs** [comment]
Right, *finally* go the UWP package to install correctly. Think this is good to merge.

**Comment by beto-rodriguez** [comment]
Awesome!, I see I was missing some files, definitively I am merging this, and publishing in Nuget asap, thanks!

**Comment by beto-rodriguez** [comment]
I am not able yet to install the package correctly, it installs and all the namespaces and objects are here, but when I run the package I get, were you able to install it and run your app?

Some how the Xaml files (default legend, default tooltip) seems not be included correctly. I even tried removed the files and build this controls just in code behind, with no success:

untitled


Any idea is appreciated
Thanks

**Comment by beto-rodriguez** [comment]
I think I got it.... it seems to be an issue with UWP packages... 

https://support.microsoft.com/en-us/kb/2739194

Microsoft give me back my time! hours! weeks!

**Comment by ibebbs** [comment]
It all 'just worked' for me. Glad to see you found a solution though.

I know what you mean about the frustrations with bugs in VS!

**Pull request merged**
