### PR TITLE
Fixed nuspec definition to be inline with Nuget spesifcation

### LINKED ISSUE #221: Incorrect Nuget Targetframework spesification
Hi

The target specification for your LiveCharts Nuget PCL package is incorrect, currently it is `portable40-net40+sl5+win8+wp8+wpa81` but portable40-net40 isn't part of the official spec, instead it should be `portable-net40+sl5+win8+wp8+wpa81`

See [here](https://docs.nuget.org/create/targetframeworks)

The package works fine when using Nuget, but when using a manager like Paket it fails to add the package as it doesn't see it as support .NETFramework.

Currently it produces the following include statement in *.csproj

`<When Condition="($(TargetFrameworkIdentifier) == 'WindowsPhoneApp') Or ($(TargetFrameworkIdentifier) == '.NETCore') Or ($(TargetFrameworkIdentifier) == 'Silverlight' And $(TargetFrameworkVersion) == 'v5.0') Or ($(TargetFrameworkIdentifier) == 'WindowsPhone' And ($(TargetFrameworkVersion) == 'v8.0' Or $(TargetFrameworkVersion) == 'v8.1')) Or ($(TargetFrameworkProfile) == 'Profile31') Or ($(TargetFrameworkProfile) == 'Profile32') Or ($(TargetFrameworkProfile) == 'Profile84') Or ($(TargetFrameworkProfile) == 'Profile157')">
      <ItemGroup>
        <Reference Include="LiveCharts">
          <HintPath>..\packages\LiveCharts\lib\portable40-net40+sl5+win8+wp8+wpa81\LiveCharts.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>`

when it should produce

`When Condition="($(TargetFrameworkIdentifier) == 'WindowsPhoneApp') Or ($(TargetFrameworkIdentifier) == '.NETCore') Or ($(TargetFrameworkIdentifier) == '.NETStandard' And ($(TargetFrameworkVersion) == 'v1.0' Or $(TargetFrameworkVersion) == 'v1.1' Or $(TargetFrameworkVersion) == 'v1.2' Or $(TargetFrameworkVersion) == 'v1.3' Or $(TargetFrameworkVersion) == 'v1.4' Or $(TargetFrameworkVersion) == 'v1.5')) Or ($(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3' Or $(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1' Or $(TargetFrameworkVersion) == 'v4.6.2')) Or ($(TargetFrameworkIdentifier) == 'Silverlight' And $(TargetFrameworkVersion) == 'v5.0') Or ($(TargetFrameworkIdentifier) == 'WindowsPhone' And ($(TargetFrameworkVersion) == 'v8.0' Or $(TargetFrameworkVersion) == 'v8.1')) Or ($(TargetFrameworkIdentifier) == 'MonoAndroid') Or ($(TargetFrameworkIdentifier) == 'MonoTouch') Or ($(TargetFrameworkIdentifier) == 'Xamarin.iOS') Or ($(TargetFrameworkIdentifier) == 'Xamarin.Mac') Or ($(TargetFrameworkProfile) == 'Profile5') Or ($(TargetFrameworkProfile) == 'Profile6') Or ($(TargetFrameworkProfile) == 'Profile7') Or ($(TargetFrameworkProfile) == 'Profile14') Or ($(TargetFrameworkProfile) == 'Profile19') Or ($(TargetFrameworkProfile) == 'Profile24') Or ($(TargetFrameworkProfile) == 'Profile31') Or ($(TargetFrameworkProfile) == 'Profile32') Or ($(TargetFrameworkProfile) == 'Profile37') Or ($(TargetFrameworkProfile) == 'Profile42') Or ($(TargetFrameworkProfile) == 'Profile44') Or ($(TargetFrameworkProfile) == 'Profile47') Or ($(TargetFrameworkProfile) == 'Profile49') Or ($(TargetFrameworkProfile) == 'Profile78') Or ($(TargetFrameworkProfile) == 'Profile84') Or ($(TargetFrameworkProfile) == 'Profile92') Or ($(TargetFrameworkProfile) == 'Profile102') Or ($(TargetFrameworkProfile) == 'Profile111') Or ($(TargetFrameworkProfile) == 'Profile136') Or ($(TargetFrameworkProfile) == 'Profile147') Or ($(TargetFrameworkProfile) == 'Profile151') Or ($(TargetFrameworkProfile) == 'Profile157') Or ($(TargetFrameworkProfile) == 'Profile158') Or ($(TargetFrameworkProfile) == 'Profile225') Or ($(TargetFrameworkProfile) == 'Profile240') Or ($(TargetFrameworkProfile) == 'Profile255') Or ($(TargetFrameworkProfile) == 'Profile259') Or ($(TargetFrameworkProfile) == 'Profile328') Or ($(TargetFrameworkProfile) == 'Profile336') Or ($(TargetFrameworkProfile) == 'Profile344')">
      <ItemGroup>
        <Reference Include="LiveCharts">
          <HintPath>..\packages\LiveCharts\lib\portable-net40+sl5+win8+wp8+wpa81\LiveCharts.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>`

### PR DESCRIPTION
**Pull request by DeadlyEmbrace**
Fixes #221

### CODE REVIEW

**Comment by beto-rodriguez** [comment]
Hello and thanks, only one issue, I agree with you nuget says that the name of the profile is as you stated, the problem is that when I pack the code with this profile, Nuget.exe packs 2 binaries.

This behavior lead me to use an unofficial project name, any clue how to solve this?

image

**Comment by beto-rodriguez** [comment]
Run the .bat file included in the root of the project, you will end with 2 binaries, an unofficial profile, created by default by Nuget.exe, and the profile you just set, the unofficial profile includes the dll debug version

**Comment by DeadlyEmbrace** [comment]
Ah, I missed that... will have to spend some time digging. Will get back to you once I've figured it out

**Comment by DeadlyEmbrace** [comment]
Ok, I've done some digging, here's what I've found:

It seems that when you call `nuget pack *.csproj` nuget automatcially packs the .dll file for you whether you want it or not (you can test this by removing the file references in the nuspec and building it) which is the reason we get two folders, one named correctly as per the nuspec and one not.
The suggested solution is to call `nuget pack` directly on the nuspec file which will then only pack the files as per the files node, however this won't work if you have Replacement Tokens like `$version$`

I've though of several workarounds, but most of them require the inclusion of extra binaries in order to extract the version number and then push it into the nuspec file or changing the version manually (:-1:)  so the version can be set correctly. A potentially simple solution might be to replace the LiveCharts.pack.bat with [CakeBuild](http://cakebuild.net/), if you want I can set one up and you can take a look at it?

I find it pretty mind-boggling that `nuget pack` produces packages for PCLs that do not conform to their spesification.

**Comment by beto-rodriguez** [comment]
CakeBuild seems awesome, if you could help me with it it would be awesome, I have never used it.

I really have no idea why Nuget is doing that.... by default it is using an unofficial name profile name...

**Comment by DeadlyEmbrace** [comment]
Yeah, CakeBuild is pretty cool, been using it for a while and it has eased builed and deployment a great deal. For now I'll write it to replicate the `LiveCharts.pack.bat` file, but later on we could change it to automate the entire build process (if you want)

Anyhow, I'll try and get it done later tonight, but otherwise somewhere over the weekend.

**Comment by DeadlyEmbrace** [comment]
Ok, I've completed the Cake script and everything seems to work correctly (I need to just double check stuff, it's pretty late here so there could be errors)
Anyhow, if you want to take a look at it, it's in my repo [here](https://github.com/DeadlyEmbrace/Live-Charts/tree/feature/CakeBuild)
I need to modify the Cake.VersionReader (it retrieves the version from the binary) at the moment it only supports SemVer so you lose the final number in your build (so 0.7.3.1 becomes 0.7.3)
I'll try to patch that up tomorrow or Saturday and submit a pull request after that is done.

**Comment by beto-rodriguez** [comment]
Thank you very much, I will take a look to it, and see how it works.

Thanks again!

**Comment by DeadlyEmbrace** [comment]
Ok. I've completed the build script so version numbers are now correctly generated.

**Comment by beto-rodriguez** [comment]
Trying this and merging (when I understand how Cake build works :smile: )

**Comment by beto-rodriguez** [comment]
Ok, I have to say that cake build is really nice, thanks for introducing me there

After that the script is not working correctly, every .dll file targets .net 4.5, I mean it packs all the versions but they are not compiled using the corresponding .net version.

I will investigate the issue, I totally like cake build, but if you could help me figuring out how to solve this image explains what I mean

untitled

**Comment by beto-rodriguez** [comment]
God dammit git... I wanted to merge this when everything was ready, but accidentally this is already part of the project, welcome to LiveCharts contributors list, any ways we need to fix this before packing with this scipt

**Comment by DeadlyEmbrace** [comment]
Ah, think I know what happened, will fix and submit again.

**Pull request merged**
