### PR TITLE
Clearing old axes before setting new ones, #432

### PR DESCRIPTION
**Pull request by rusanov-vladimir**
#### Summary

Clearing old axes before setting new ones

#### Solves 

#432

### CODE REVIEW

**Comment by gzapataw** [comment]
This can be done with the method AxisY.Clear()
i.e. cartesianChart1.AxisY.Clear();  cartesianChart1.AxisX.Clear();

**Comment by rusanov-vladimir** [comment]
Well, correct me if wrong, but that's exactly what I'm doing...  I don't have UI object of the existing axes directly, so I'm getting them from `AxisCore` and then calling `Clean`. If you meant that I can clear the old axes manually before setting up new one - that's seems to be a workaround rather the fix.

**Comment by gzapataw** [comment]
@rusanov-vladimir You're completely right, mine was just a workaround...

**Comment by beto-rodriguez** [comment]
Thanks again @rusanov-vladimir, I just extended your solution to UWP and merged

**Pull request merged**
