### PR TITLE
UWP support

### PR DESCRIPTION
**Pull request by AuroraDysis**
I'm still working in progress. Don't merge until I finish it.
# Roadmap
- [x] Change namespace
- [x] Add StringFormatConverter to instead of StringFormat
- [x] Converter compatibility
- [x] MultiBinding compatibility, use MultiBindingBehavior in [Cimbalino.Toolkit](https://github.com/Cimbalino/Cimbalino-Toolkit/blob/master/src/Cimbalino.Toolkit%20(WP8)/Behaviors/MultiBindingBehavior.cs)
- [x] Geometry.Parse not exist. Solution References:
 + [Is there a way to parse a vector path geometry in UWP in code behind?](http://stackoverflow.com/questions/34880793/is-there-a-way-to-parse-a-vector-path-geometry-in-uwp-in-code-behind) **Current Solution**
 + [Setting Path.Data in code-behind](http://stackoverflow.com/questions/31019687/setting-path-data-in-code-behind)
 + [Silverlight String-To-PathGeometry Converter](https://stringtopathgeometry.codeplex.com/SourceControl/latest#PathConverter/PathConverter/StringToPathGeometryConverter.cs)
- [x] use VariableSizedWrapGrid instead of WrapPanel
- [x] There is no TypeConverter class in uwp [**Removed**]
[WinRT Replacement for System.ComponentModel.TypeConverter](http://stackoverflow.com/questions/12495937/winrt-replacement-for-system-componentmodel-typeconverter)
- [x] There is no Effect class in uwp [**Removed**] (Use Windows.UI.Composition instead)
- [x] Transform compatibility
- [x] RelativeSource compatibility
- [x] Panel.ZIndex compatibility
- [x] Grid.IsSharedSizeScope compatibility (**Now only move all shared size in comment**, use search to find them)
- [x] ClipToBounds compatibility (**Now only move all ClipToBounds in comment**)
- [x] Animation compatibility
- [x] SetCurrentValue compatibility (**Move to comment and replace by SetValue**)
- [x] FrameworkPropertyMetadata compatibility [**Only replace by PropertyMetadata**]
- [x] DefiningGeometry compatibility [**Only Removed**]
- [ ] Gestrue compatibility (**Need to reconsider**)
- [x] Canvas.SetRight
- [x] Brush.Clone compatibility(Remove in three place *temporarily*)
- [x] http://stackoverflow.com/questions/31144019/how-to-set-a-nullable-property-value-by-style-setter (**Now add a Auto to instead null**)
- [ ] Add Samples and fix bug
- [ ] Clean code

### CODE REVIEW

**Comment by AuroraDysis** [comment]
Roadmap
- [x] Change namespace
- [x] Add StringFormatConverter to instead of StringFormatConverter
- [x] Converter compatibility
- [ ] Transform compatibility
- [ ] RelativeSource compatibility
- [ ] Panel.ZIndex compatibility
- [ ] Grid.IsSharedSizeScope compatibility
- [ ] ClipToBounds compatibility
- [ ] MultiBinding compatibility
- [ ]  Drag compatibility

**Comment by beto-rodriguez** [comment]
This will be awesome, thanks!

**Comment by beto-rodriguez** [comment]
I was trying not to touch WpfView project, while you were working on this. 

But after thinking about it, I need to, for high performance charts we also need "scroll bar charts" like this they do here

https://www.amcharts.com/demos/multiple-data-sets/?theme=black

So I will add this feature, don't worry if you don't update that part of the code, I will

**Comment by AuroraDysis** [comment]
Build success, but there is still a lot of work to do.

**Comment by beto-rodriguez** [comment]
I will take a look, thanks for this huge help!

**Comment by beto-rodriguez** [comment]
Trying to work in your branch, but then I get 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1566	Error reading resource 'LiveCharts.Uwp.Properties.UwpView.rd.xml' -- 'Could not find file 'C:\Users\btord\Source\Repos\Live-Charts\UwpView\Properties\UwpView.rd.xml'.'	UwpView	C:\Users\btord\Source\Repos\Live-Charts\UwpView\CSC	1	Active

Did you missed that file?

**Comment by beto-rodriguez** [comment]
Never mind, it is an practically empty file, I added it

**Comment by AuroraDysis** [comment]
Debug may take a long time, more changes than I thought

**Comment by beto-rodriguez** [comment]
Well, we are on the way, time will make this real.

this weekend High performance should be ready, then I will help you hard on this.

**Comment by AuroraDysis** [comment]
I forgot to check "Allow edits from maintainers". Now you have authority.

**Comment by beto-rodriguez** [comment]
I will start debugging this, I hope you don't mind if I add some comments to your code so I get a better idea why you did some stuff.

Again thanks!

**Comment by beto-rodriguez** [comment]
Since this PR is huge, I created a branch for UWP platform support, and added you as a collaborator.

Lets continue this work in the branch.

If I did things right you should be able now to commit to Live-Charts branches once you accept the invitation.

**Pull request closed without merging**
