### PR TITLE
Updates for bindability

### PR DESCRIPTION
**Pull request by gregsdennis**
I have successfully updated the library to support binding series now.  There have been a few other enhancements as well, mostly around not crashing when bindings haven't yet initialized.  Feel free to ask questions.

### CODE REVIEW

**Comment by beto-rodriguez** [comment]
Awesome Thank you very much.

**Comment by gregsdennis** [comment]
Absolutely.  I like what you've done, and I'd like to help out more, where I can.

**Comment by gregsdennis** [comment]
Any idea when you'll be able to update Nuget?

**Comment by beto-rodriguez** [comment]
I think that the changes you made changed a lot this library, so I am trying to add that to documentation and better examples. I think that before the next release we need to make it clear for everyone

**Comment by gregsdennis** [comment]
Understandable.  Let me know where I can help.

**Pull request merged**
