### PR TITLE
Add a new series - candle series

### PR DESCRIPTION
**Pull request by hulihutu9**
Candle series is a financial series for stock. It is almost identical to Ohlc series, looks like a candle. So I add 3 new files and not change other files.

### CODE REVIEW

**Comment by beto-rodriguez** [comment]
Thank you very much, just merged your changes, I am really glad you could build a new series without asking me any question about how the library works :smile: 

Really thanks!

**Comment by hulihutu9** [comment]
I'm a beginner for C#, writing a small program about stock. I looked for a better WPF chart control  and found your work. 

Thanks a lot for your work! It makes chart fantastic and everyone can change it. My work is just based your codes. It will be better If there are some documents to describe the library structure.

**Comment by PsykotropyK** [comment]
Hello beto-rodriguez, hulihutu9,

I have not yet used your charts but it look super promising. My only drawback was that there was no candles series, at least from reading the documentation. Should I understand from this post that this kind of series is now available?

Thanks

**Comment by beto-rodriguez** [comment]
@PsykotropyK it is, hope you give the library a try and it is useful for you

**Comment by PsykotropyK** [comment]
I will :)

**Pull request merged**
